modules/admin/controllers/CategoryController.php
<?php
namespace printclick\modules\admin\controllers;

use Yii;
use yii\data\ActiveDataProvider;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\web\ServerErrorHttpException;
use yii\filters\AccessControl;
use printclick\models\Category;
use printclick\modules\admin\models\CategoryForm;

/**
 */
class CategoryController extends Controller
{
    public $layout = 'main';

    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'rules' => [
                    [
                        'allow'     => true,
                        'actions'   => ['list', 'view', 'create', 'update', 'delete'],
                        'roles'     => ['@'],
                    ],
                ],
            ],
        ];
    }

    public function actionList()
    {
        $categories = new ActiveDataProvider([
            'query'         => Category::find()->orderByTree(),
            'pagination'    => false,
        ]);

        return $this->render('list', ['categories' => $categories]);
    }

    public function actionView($id)
    {
        $category = Category::findOne($id);
        if ($category === null) {
            throw new NotFoundHttpException('Категория не найдена');
        }

        return $this->render('view', ['category' => $category]);
    }

    public function actionCreate()
    {
        $category = new Category();

        $form = new CategoryForm($category);
        if ($form->load(Yii::$app->request->post()) && $form->save()) {
            return $this->redirect(['view', 'id' => $category->id]);
        }

        return $this->render('create', [
            'model' => $form,
            'list'  => Category::find()->orderByTree()->all(),
        ]);
    }

    public function actionUpdate($id)
    {
        $category = Category::findOne($id);
        if ($category === null) {
            throw new NotFoundHttpException('Категория не найдена');
        }

        $form = new CategoryForm($category);
        if ($form->load(Yii::$app->request->post()) && $form->save()) {
            return $this->redirect(['view', 'id' => $category->id]);
        }

        return $this->render('update', [
            'model' => $form,
            'list'  => Category::find()->orderByTree()->all(),
        ]);
    }

    public function actionDelete($id)
    {
        $category = Category::findOne($id);
        if ($category === null) {
            throw new NotFoundHttpException('Категория не найдена');
        }

        if (Yii::$app->request->isPost) {
            if (!$category->deleteWithChildren()) {
                throw new ServerErrorHttpException('Невозможно удалить категорию');
            }

            return $this->redirect(['list']);
        }

        return $this->render('delete', ['category' => $category]);
    }
}

modules/admin/controllers/NewsController.php
<?php
namespace printclick\modules\admin\controllers;

use Yii;
use yii\data\ActiveDataProvider;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\web\ServerErrorHttpException;
use yii\filters\AccessControl;
use printclick\models\Category;
use printclick\models\News;

/**
 */
class NewsController extends Controller
{
    public $layout = 'main';

    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'rules' => [
                    [
                        'allow'     => true,
                        'actions'   => ['list', 'view', 'create', 'update', 'delete'],
                        'roles'     => ['@'],
                    ],
                ],
            ],
        ];
    }

    public function actionList()
    {
        $news = new ActiveDataProvider([
            'query'         => News::find(),
            'pagination'    => false,
        ]);

        return $this->render('list', ['news' => $news]);
    }

    public function actionView($id)
    {
        $news = News::findOne($id);
        if ($news === null) {
            throw new NotFoundHttpException('Новость не найдена');
        }

        return $this->render('view', ['news' => $news]);
    }

    public function actionCreate()
    {
        $news = new News();

        if ($news->load(Yii::$app->request->post()) && $news->save()) {
            return $this->redirect(['view', 'id' => $news->id]);
        }

        return $this->render('create', [
            'news'          => $news,
            'categories'    => Category::find()->orderByTree()->all(),
        ]);
    }

    public function actionUpdate($id)
    {
        $news = News::findOne($id);
        if ($news === null) {
            throw new NotFoundHttpException('Новость не найдена');
        }

        if ($news->load(Yii::$app->request->post()) && $news->save()) {
            return $this->redirect(['view', 'id' => $news->id]);
        }

        return $this->render('update', [
            'news'          => $news,
            'categories'    => Category::find()->orderByTree()->all(),
        ]);
    }

    public function actionDelete($id)
    {
        $news = News::findOne($id);
        if ($news === null) {
            throw new NotFoundHttpException('Новость не найдена');
        }

        if (Yii::$app->request->isPost) {
            if (!$news->delete()) {
                throw new ServerErrorHttpException('Невозможно удалить новость');
            }

            return $this->redirect(['list']);
        }

        return $this->render('delete', ['news' => $news]);
    }
}

modules/admin/views/news/_form.php
<?php
/**
 * @var yii\web\View $this
 * @var printclick\models\News $news
 * @var printclick\models\Category[] $categories
 */
use yii\bootstrap\ActiveForm;
use yii\helpers\Html;

$dropDown = [];
foreach ($categories as $item) {
    $dropDown[$item->id] = ($item->dpt ? str_repeat('—', $item->dpt) . ' ' : '') .
        $item->name;
}
?>
<div id="news-form">
    <?php
    $form = ActiveForm::begin([
        'options' => [
            'class' => 'form-vertical',
        ],
    ]);

    echo $form->field($news, 'title')->textInput();
    echo $form->field($news, 'category_id')->dropDownList($dropDown, ['prompt' => '- выбрать -']);
    echo $form->field($news, 'status')->dropDownList($news->statusList());
    echo $form->field($news, 'excerpt')->textarea(['rows' => 3]);
    echo $form->field($news, 'content')->textarea(['rows' => 15]);
    ?>

    <div class="form-actions">
        <?= Html::submitButton($news->isNewRecord ? 'Создать' : 'Сохранить',
            ['class' => 'btn btn-primary']) ?>
    </div>

    <?php ActiveForm::end(); ?>
</div>

modules/admin/views/news/_item.php
<?php
/**
 * @var yii\web\View $this
 * @var printclick\models\News $model
 */
use yii\helpers\Html;
use printclick\models\News;

?>
<div class="media news-item">
    <div class="media-body">
        <h3 class="media-heading"><?= Html::a(Html::encode($model->title), ['view', 'id' => $model->id]) ?></h3>
        <p>
            <i><span class="label <?= $model->status === News::STATUS_DRAFT ? 'label-default' : 'label-success' ?>"><?= $model->statusName ?></span></i>
            <i>в <?= Html::a(Html::encode($model->category->name), ['category/view', 'id' => $model->category->id])?></i>
            <i>от <?= Yii::$app->formatter->asDatetime($model->create_date) ?></i>
        </p>
        <p><?= Yii::$app->formatter->asNtext($model->excerpt) ?></p>
    </div>
</div>

modules/admin/views/news/create.php
<?php
/**
 * @var yii\web\View $this
 * @var printclick\models\News $news
 * @var printclick\models\Category[] $categories
 */

$this->title    = 'Добавить новость';
$this->params   = [
    'breadcrumbs'   => [
        [
            'label' => 'Новости',
            'url'   => ['list'],
        ],
        [
            'label' => 'Новая',
        ],
    ],
];
?>
<div id="news-create">
    <?= $this->render('_form', ['news' => $news, 'categories' => $categories]) ?>
</div>

modules/admin/views/news/delete.php
<?php
/**
 * @var yii\web\View $this
 * @var printclick\models\News $news
 */
use yii\helpers\Html;

$this->title    = sprintf('Удалить новость "%s"', $news->title);
$this->params   = [
    'breadcrumbs'   => [
        [
            'label' => 'Новости',
            'url'   => ['list'],
        ],
        [
            'label' => $news->title,
            'url'   => ['view', 'id' => $news->id],
        ],
        [
            'label' => 'Удалить',
        ],
    ],
];
?>
<div id="news-delete">
    <?= Html::beginForm() ?>

    <div class="alert alert-warning">
        <h4>Внимание!</h4>
        <p>Новость будет удалена безвозвратно!</p>
    </div>

    <div class="form-actions">
        <?= Html::submitButton('Удалить новость', ['class' => 'btn btn-danger']) ?>
    </div>

    <?= Html::endForm() ?>
</div>

modules/admin/views/news/list.php
<?php
/**
 * @var yii\web\View $this
 * @var yii\data\ActiveDataProvider $news
 */
use yii\widgets\ListView;

$this->title    = 'Новости';
$this->params   = [
    'breadcrumbs'   => [
        [
            'label' => 'Новости',
        ],
    ],
    'actions'       => [
        [
            'label' => 'Создать',
            'url'   => ['create'],
        ],
    ],
];
?>
<div id="news-list">
    <?= ListView::widget([
        'dataProvider'  => $news,
        'itemView'      => '_item',
    ]) ?>
</div>

modules/admin/views/news/update.php
<?php
/**
 * @var yii\web\View $this
 * @var printclick\models\News $news
 * @var printclick\models\Category[] $categories
 */

$this->title    = sprintf('Изменить новость "%s"', $news->title);
$this->params   = [
    'breadcrumbs'   => [
        [
            'label' => 'Новости',
            'url'   => ['list'],
        ],
        [
            'label' => $news->title,
            'url'   => ['view', 'id' => $news->id],
        ],
        [
            'label' => 'Редактировать',
        ],
    ],
];
?>
<div id="news-update">
    <?= $this->render('_form', ['news' => $news, 'categories' => $categories]) ?>
</div>

modules/admin/views/news/view.php
<?php
/**
 * @var yii\web\View $this
 * @var printclick\models\News $news
 */
use yii\widgets\DetailView;
use yii\helpers\Html;

$this->title    = $news->title;
$this->params   = [
    'breadcrumbs'   => [
        [
            'label' => 'Новости',
            'url'   => ['list'],
        ],
        [
            'label' => $news->title,
        ],
    ],
    'actions'       => [
        [
            'label' => 'Редактировать',
            'url'   => ['update', 'id' => $news->id],
        ],
        [
            'label' => 'Удалить',
            'url'   => ['delete', 'id' => $news->id],
        ],
    ],
];
?>
<div id="news-view">
    <?= DetailView::widget([
        'model'         => $news,
        'attributes'    => [
            'title',
            'statusName',
            [
                'label'     => 'URL',
                'value'     => Yii::$app->urlManager->createAbsoluteUrl(['/news/view', 'slug' => $news->slug]),
                'format'    => 'url',
            ],
            [
                'label'     => 'Категория',
                'value'     => Html::a(Html::encode($news->category->name), ['category/view', 'id' => $news->category->id]),
                'format'    => 'raw',
            ],
            'excerpt:ntext',
            'content:ntext',
        ],
    ]) ?>
</div>