modules/admin/controllers/CategoryController.php
<?php
namespace printclick\modules\admin\controllers;

use Yii;
use yii\data\ActiveDataProvider;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\web\ServerErrorHttpException;
use yii\filters\AccessControl;
use printclick\models\Category;
use printclick\modules\admin\models\CategoryForm;

/**
 */
class CategoryController extends Controller
{
    public $layout = 'main';

    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'rules' => [
                    [
                        'allow'     => true,
                        'actions'   => ['list', 'view', 'create', 'update', 'delete'],
                        'roles'     => ['@'],
                    ],
                ],
            ],
        ];
    }

    public function actionList()
    {
        $categories = new ActiveDataProvider([
            'query'         => Category::find()->orderByTree(),
            'pagination'    => false,
        ]);

        return $this->render('list', ['categories' => $categories]);
    }

    public function actionView($id)
    {
        $category = Category::findOne($id);
        if ($category === null) {
            throw new NotFoundHttpException('Категория не найдена');
        }

        return $this->render('view', ['category' => $category]);
    }

    public function actionCreate()
    {
        $category = new Category();

        $form = new CategoryForm($category);
        if ($form->load(Yii::$app->request->post()) && $form->save()) {
            return $this->redirect(['view', 'id' => $category->id]);
        }

        return $this->render('create', [
            'model' => $form,
            'list'  => Category::find()->orderByTree()->all(),
        ]);
    }

    public function actionUpdate($id)
    {
        $category = Category::findOne($id);
        if ($category === null) {
            throw new NotFoundHttpException('Категория не найдена');
        }

        $form = new CategoryForm($category);
        if ($form->load(Yii::$app->request->post()) && $form->save()) {
            return $this->redirect(['view', 'id' => $category->id]);
        }

        return $this->render('update', [
            'model' => $form,
            'list'  => Category::find()->orderByTree()->all(),
        ]);
    }

    public function actionDelete($id)
    {
        $category = Category::findOne($id);
        if ($category === null) {
            throw new NotFoundHttpException('Категория не найдена');
        }

        if (Yii::$app->request->isPost) {
            if (!$category->deleteWithChildren()) {
                throw new ServerErrorHttpException('Невозможно удалить категорию');
            }

            return $this->redirect(['list']);
        }

        return $this->render('delete', ['category' => $category]);
    }
}

modules/admin/controllers/NewsController.php
<?php
namespace printclick\modules\admin\controllers;

use Yii;
use yii\data\ActiveDataProvider;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\web\ServerErrorHttpException;
use yii\filters\AccessControl;
use printclick\models\Category;
use printclick\models\News;

/**
 */
class NewsController extends Controller
{
    public $layout = 'main';

    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'rules' => [
                    [
                        'allow'     => true,
                        'actions'   => ['list', 'view', 'create', 'update', 'delete'],
                        'roles'     => ['@'],
                    ],
                ],
            ],
        ];
    }

    public function actionList()
    {
        $news = new ActiveDataProvider([
            'query'         => News::find(),
            'pagination'    => false,
        ]);

        return $this->render('list', ['news' => $news]);
    }

    public function actionView($id)
    {
        $news = News::findOne($id);
        if ($news === null) {
            throw new NotFoundHttpException('Новость не найдена');
        }

        return $this->render('view', ['news' => $news]);
    }

    public function actionCreate()
    {
        $news = new News();

        if ($news->load(Yii::$app->request->post()) && $news->save()) {
            return $this->redirect(['view', 'id' => $news->id]);
        }

        return $this->render('create', [
            'news'          => $news,
            'categories'    => Category::find()->orderByTree()->all(),
        ]);
    }

    public function actionUpdate($id)
    {
        $news = News::findOne($id);
        if ($news === null) {
            throw new NotFoundHttpException('Новость не найдена');
        }

        if ($news->load(Yii::$app->request->post()) && $news->save()) {
            return $this->redirect(['view', 'id' => $news->id]);
        }

        return $this->render('update', [
            'news'          => $news,
            'categories'    => Category::find()->orderByTree()->all(),
        ]);
    }

    public function actionDelete($id)
    {
        $news = News::findOne($id);
        if ($news === null) {
            throw new NotFoundHttpException('Новость не найдена');
        }

        if (Yii::$app->request->isPost) {
            if (!$news->delete()) {
                throw new ServerErrorHttpException('Невозможно удалить новость');
            }

            return $this->redirect(['list']);
        }

        return $this->render('delete', ['news' => $news]);
    }
}

modules/admin/controllers/UserController.php
<?php
namespace printclick\modules\admin\controllers;

use Yii;
use yii\web\Controller;
use yii\filters\AccessControl;
use yii\filters\VerbFilter;
use printclick\modules\admin\models\LoginForm;

/**
 */
class UserController extends Controller
{
    public $layout = 'login';

    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            'access' => [
                'class'     => AccessControl::className(),
                'rules'     => [
                    [
                        'allow'     => true,
                        'actions'   => ['login'],
                        'roles'     => ['?'],
                    ],
                    [
                        'allow'     => true,
                        'actions'   => ['logout'],
                        'roles'     => ['@'],
                    ],
                ],
            ],
            'verbs' => [
                'class'     => VerbFilter::className(),
                'actions'   => [
                    'logout' => ['post'],
                ],
            ],
        ];
    }

    public function actionLogin()
    {
        if (!Yii::$app->user->isGuest) {
            return $this->goHome();
        }

        $model = new LoginForm();
        if ($model->load(Yii::$app->request->post()) && $model->login()) {
            return $this->goBack();
        }

        return $this->render('login', ['model' => $model]);
    }

    public function actionLogout()
    {
        Yii::$app->user->logout();

        return $this->goHome();
    }
}

modules/admin/views/layouts/login.php
<?php
/**
 * @var yii\web\View $this
 * @var string $content
 */
use yii\helpers\Html;
use printclick\modules\admin\assets\LayoutAsset;

LayoutAsset::register($this);
?>
<?php $this->beginPage() ?>
<!DOCTYPE html>
<html lang="<?= Yii::$app->language ?>">
<head>
    <meta charset="<?= Yii::$app->charset ?>"/>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <?= Html::csrfMetaTags() ?>
    <title><?= Html::encode($this->title) ?></title>
    <?php $this->head() ?>
</head>
<body>
    <?php $this->beginBody() ?>
    <div class="container">
        <div class="row">
            <div class="col-md-6 col-md-offset-3 col-sm-8 col-sm-offset-2">
                <?= $content ?>
            </div>
        </div>
    </div>
    <?php $this->endBody() ?>
</body>
</html>
<?php $this->endPage() ?>

modules/admin/views/layouts/main.php
<?php
/**
 * @var yii\web\View $this
 * @var string $content
 */
use yii\helpers\Html;
use yii\bootstrap\Nav;
use yii\bootstrap\NavBar;
use yii\bootstrap\ButtonDropdown;
use yii\widgets\Breadcrumbs;
use printclick\modules\admin\assets\LayoutAsset;

LayoutAsset::register($this);
?>
<?php $this->beginPage() ?>
<!DOCTYPE html>
<html lang="<?= Yii::$app->language ?>">
<head>
    <meta charset="<?= Yii::$app->charset ?>"/>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <?= Html::csrfMetaTags() ?>
    <title><?= Html::encode($this->title) ?></title>
    <?php $this->head() ?>
</head>
<body>

<?php $this->beginBody() ?>
<div class="wrap">
    <?php
    NavBar::begin([
        'brandLabel'    => 'Администрирование',
        'brandUrl'      => ['/admin'],
    ]);

    echo Nav::widget([
        'options'   => [
            'class' => 'navbar-nav navbar-left',
        ],
        'items'     => [
            [
                'label'     => 'Категории',
                'url'       => ['category/list'],
                'active'    => Yii::$app->controller->id === 'category',
            ],
            [
                'label'     => 'Новости',
                'url'       => ['news/list'],
                'active'    => Yii::$app->controller->id === 'news',
            ],
        ],
    ]);

    echo Nav::widget([
        'options'   => [
            'class' => 'navbar-nav navbar-right',
        ],
        'items'     => [
            [
                'label'         => 'Выход',
                'url'           => ['user/logout'],
                'linkOptions'   => ['data-method' => 'post'],
            ],
        ],
    ]);

    NavBar::end();
    ?>

    <div class="container">
        <div class="row">
            <div class="col-md-10 col-sm-8">
                <?= Breadcrumbs::widget([
                    'homeLink'  => false,
                    'links'     => isset($this->params['breadcrumbs']) ? $this->params['breadcrumbs'] : [],
                ]) ?>
            </div>

            <?php if (!empty($this->params['actions'])): ?>
                <div class="col-md-2 col-sm-4">
                    <?= ButtonDropdown::widget([
                        'label'             => 'Действия',
                        'options'           => ['class' => 'btn btn-default'],
                        'containerOptions'  => ['class' => 'pull-right'],
                        'dropdown'          => ['items' => $this->params['actions']],
                    ]) ?>
                </div>
            <?php endif ?>
        </div>
    </div>

    <div class="container">
        <h1 class="page-header" style="margin-top: 0"><?= Html::encode($this->title) ?></h1>
    </div>

    <div class="container">
        <?= $content ?>
    </div>
</div>

<?php $this->endBody() ?>
</body>
</html>
<?php $this->endPage() ?>